use_frameworks!

target 'MHNetWorkManager_Example' do
  pod 'MHNetWorkManager', :path => '../'

  target 'MHNetWorkManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
